services:
  - type: web
    name: flask-chat-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      # These environment variables will need to be set in Render's dashboard
      # - key: DATABASE_URL
      #   sync: false
      # - key: FLASK_SECRET_KEY
      #   sync: false
      # - key: GOOGLE_OAUTH_CLIENT_ID
      #   sync: false
      # - key: GOOGLE_OAUTH_CLIENT_SECRET
      #   sync: false